title: AGNTCY Blogs
logo: /assets/images/logo-light.svg
logo_dark: /assets/images/logo-dark.svg
description: >- # this means to ignore newlines until "baseurl:"
  Building infrastructure for the Internet of Agents
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blogs.agntcy.org" # the base hostname & protocol for your site, e.g. http://example.com

github_url: "https://github.com/agntcy"
linkedin_url: "https://www.linkedin.com/company/agntcyproject"
youtube_url: "https://www.youtube.com/@agntcy-lf"
slack_url: "https://join.slack.com/t/agntcy/shared_invite/zt-3hb4p7bo0-5H2otGjxGt9OQ1g5jzK_GQ"

# Header navigation - explicitly list pages to show
header_pages:
  - archive.md
  - about.md

# Show excerpts on home page
show_excerpts: true
excerpt_separator: <!--more-->

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
paginate: 5
paginate_path: "/page/:num/"
